# Generated by Django 6.0.2 on 2026-02-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='metodo_pago',
            field=models.CharField(choices=[('BIZUM', 'Bizum'), ('TRASPASO', 'Traspaso'), ('TRANSFERENCIA', 'Transferencia'), ('TRASPASO', 'Traspaso'), ('TARJETA', 'Tarjeta'), ('EFECTIVO', 'Efectivo')], max_length=50),
        ),
    ]
