# Generated by Django 6.0.2 on 2026-02-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registro_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Gasto', 'Gasto'), ('Ingreso', 'Ingreso')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='metodo_pago',
            field=models.CharField(choices=[('Bizum', 'Bizum'), ('Traspaso', 'Traspaso'), ('Transferencia', 'Transferencia'), ('Traspaso', 'Traspaso'), ('Tarjeta', 'Tarjeta'), ('Efectivo', 'Efectivo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo',
            field=models.CharField(choices=[('Gasto', 'Gasto'), ('Ingreso', 'Ingreso')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='tipo',
            field=models.CharField(choices=[('Gasto', 'Gasto'), ('Ingreso', 'Ingreso')], max_length=10),
        ),
    ]
